language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  # Tagging
  - docker tag udagram-api-feed kanchannannavare/udagram-api-feed
  - docker tag udagram-api-user kanchannannavare/udagram-api-user
  - docker tag udagram-frontend kanchannannavare/udagram-frontend
  - docker tag udagram-reverseproxy kanchannannavare/udagram-reverseproxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push /kanchannannavare/udagram-api-feed
  - docker push /kanchannannavare/udagram-api-user
  - docker push /kanchannannavare/udagram-frontend
  - docker push /kanchannannavare/udagram-reverseproxy

