# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t udagram-reverseproxy ./udagram-reverseproxy

# Tagging
- docker tag udagram-api-feed kanchannannavare/udagram-api-feed
- docker tag udagram-api-user kanchannannavare/udagram-api-user
- docker tag udagram-frontend kanchannannavare/udagram-frontend
- docker tag udagram-reverseproxy kanchannannavare/udagram-reverseproxy

# Push
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push /kanchannannavare/udagram-api-feed
- docker push /kanchannannavare/udagram-api-user
- docker push /kanchannannavare/udagram-frontend
- docker push /kanchannannavare/udagram-reverseproxy